//! The demo's own ingest, end to end: a loopback origin Comms is allowed to
//! fetch, and a loopback port it is not.
//!
//! `src/media.rs`'s unit tests prove the address policy and the origin matcher
//! against literals, and `src/config.rs`'s prove the normaliser. None of them
//! joins the three. This one does, over a real socket: a config file naming an
//! origin -> `check_destination` -> a GET that returns a page -> an extracted
//! item. That chain is what `tools/demo-up` runs on every pull request
//! (`demo/README.md`), so a guard that refuses it does not fail a test, it
//! fails CI on an unrelated branch.
//!
//! One `#[test]`, because it sets `SJEL_COMMS_CONFIG` and Rust runs a test
//! binary's tests as threads of one process.

use std::io::{BufRead, BufReader, Write};
use std::net::TcpListener;

const PAGE: &str = "<html><head><title>A demo article</title></head><body><article>\
     <p>Loopback origins are the whole reason the allowlist exists. The demo stands one \
     up on this machine and asks Comms to go and read it, which is the behaviour the \
     published corpus is a recording of.</p>\
     <p>The extractor needs enough prose here to return something rather than nothing, \
     because an extractor that came back empty stores nothing at all.</p>\
     </article></body></html>";

/// A one-page HTTP origin on a free loopback port. Returns the port and leaves
/// the thread serving until the test process ends.
fn serve_one_page() -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").expect("a free loopback port");
    let port = listener.local_addr().unwrap().port();
    std::thread::spawn(move || {
        for stream in listener.incoming() {
            let Ok(mut stream) = stream else { continue };
            // Read to the end of the request head, or the client waits for a
            // body this origin never asked for.
            let mut reader = BufReader::new(stream.try_clone().unwrap());
            let mut line = String::new();
            while reader.read_line(&mut line).unwrap_or(0) > 0 {
                if line == "\r\n" || line == "\n" {
                    break;
                }
                line.clear();
            }
            let response = format!(
                "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\n\
                 Content-Length: {}\r\nConnection: close\r\n\r\n{PAGE}",
                PAGE.len()
            );
            let _ = stream.write_all(response.as_bytes());
        }
    });
    port
}

#[test]
fn a_listed_loopback_origin_is_fetched_and_its_neighbours_are_not() {
    let port = serve_one_page();

    let dir = std::env::temp_dir().join(format!(
        "axon-comms-allowlist-{}-{}",
        std::process::id(),
        port
    ));
    std::fs::create_dir_all(&dir).expect("a writable temp directory");
    // The shape `tools/demo-up`'s write_comms_config emits, unknown `_note`
    // included, so this reads the demo's file and not a tidier relative of it.
    let config = dir.join("comms.json");
    std::fs::write(
        &config,
        format!(
            "{{\n  \"_note\": \"GENERATED by tools/demo-up.\",\n               \"api_secret_file\": \"\",\n               \"ingest_allowed_origins\": [\"http://127.0.0.1:{port}\"]\n}}\n"
        ),
    )
    .expect("the temp config is writable");
    std::env::set_var("SJEL_COMMS_CONFIG", &config);

    // What tools/demo-seed posts for each of its articles: a loopback URL and
    // no content, so the server fetches and extracts the page itself.
    let item = comms::media::fetch(&format!("http://127.0.0.1:{port}/articles/a-demo-article"))
        .expect("the listed origin is fetched");
    assert_eq!(item.title.as_deref(), Some("A demo article"));
    assert!(
        item.transcript
            .as_deref()
            .unwrap_or_default()
            .contains("Loopback origins"),
        "the page's own text is what got extracted: {:?}",
        item.transcript
    );

    // The neighbouring port on the same host is a different origin, and every
    // Axon service is a neighbour of the demo origin. Refused before a socket
    // is opened, so this asserts a policy and connects to nothing.
    let err = comms::media::fetch(&format!("http://127.0.0.1:{}/api/plans", port + 1))
        .expect_err("a port the config did not name stays refused");
    assert!(
        err.to_string().contains("resolves to a non-public address"),
        "unexpected error: {err}"
    );

    std::env::remove_var("SJEL_COMMS_CONFIG");

    std::env::remove_var("AXON_COMMS_CONFIG");
    let _ = std::fs::remove_dir_all(&dir);
}
