#!/bin/bash
# generate-architecture.sh — regenerate ARCHITECTURE.md from the manifests + tree.
# ARCHITECTURE.md is a build artifact (see CONTRIBUTING.md, "Generated architecture"):
# never hand-edit it, re-run this script instead. bash 3.2-safe (macOS stock bash), no
# mapfile/readarray.
#
# Usage: tools/generate-architecture.sh
# Verify without writing back: tools/check-architecture-fresh.sh
set -e

_toollib="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/lib" && pwd)"
source "$_toollib/paths.sh"

# Override for tools/check-architecture-fresh.sh: a gate must never mutate what it
# checks -- ARCHITECTURE_OUT lets it generate into a scratch file and diff, instead
# of writing in place.
OUT="${ARCHITECTURE_OUT:-$SJEL_ROOT/ARCHITECTURE.md}"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
UP="$SJEL_ROOT/upstreams.toml"
SYS="$SJEL_ROOT/systems.toml"
AX="$SJEL_ROOT/axon.toml"

{
  echo "# Sjel Architecture"
  echo
  echo "> Auto-generated by tools/generate-architecture.sh. Do not edit manually."
  echo "> Generated: $NOW | Source: axon.toml + upstreams.toml + systems.toml + capabilities/ + Packs/"
  echo
  echo "See the [engineering doctrine](CONTRIBUTING.md#engineering-doctrine) this generated view reflects."
  echo

  echo "## Capabilities"
  echo
  echo "| Capability | What | Service | Port | Panel |"
  echo "|---|---|---|---|---|"
  for dir in "$SJEL_ROOT"/capabilities/*/; do
    [ -d "$dir" ] || continue
    # No README.md means this is scaffolding, not a capability yet
    # (CONTRIBUTING.md#documentation-stays-owned-and-current). The row it produced was empty in the
    # What column anyway, so skipping it costs nothing and keeps scaffolding out of a
    # document that describes what exists.
    [ -f "$dir/README.md" ] || continue
    name="$(basename "$dir")"
    desc="$(awk '/^# /{h=1;next} h{ if (!NF) { if (got) exit; else next }; got=1; printf "%s ", $0 }' "$dir/README.md")"
    trimmed="${desc%%. *}"
    if [ "$trimmed" != "$desc" ]; then desc="$trimmed."; else desc="${desc% }"; fi
    # Port and panel read from the same manifest the Service column already opens
    # (Axon#39). Emitting them is what stops a port number living in two homes — the
    # manifest and a hand-maintained table in dashboard/README.md — since a generated
    # column cannot drift from its source. The Panel column is a dash for every
    # capability today because none declares panel_port/panel_path yet; it is emitted
    # anyway so the first one that does gets carried in by the freshness gate without a
    # generator change.
    svc="—"
    port="—"
    panel="—"
    if [ -f "$dir/service.toml" ]; then
      img="$(toml_get image "$dir/service.toml")"
      tag="$(toml_get tag "$dir/service.toml")"
      if [ -n "$img" ]; then svc="$img:$tag"; fi
      p="$(toml_get port "$dir/service.toml")"
      if [ -n "$p" ]; then port="\`$p\`"; fi
      pp="$(toml_get panel_port "$dir/service.toml")"
      pa="$(toml_get panel_path "$dir/service.toml")"
      if [ -n "$pp" ] || [ -n "$pa" ]; then panel="\`${pp:-$p}${pa}\`"; fi
    fi
    echo "| \`$name\` | $desc | $svc | $port | $panel |"
  done
  echo

  echo "## Dashboard (spine shell)"
  echo
  echo "The spine's one app — discovers installed capabilities via their manifests and mounts"
  echo "their panels; owns no domain, no data. See [Three architectural nouns](CONTRIBUTING.md#three-architectural-nouns)."
  echo
  echo "| App | What | Port |"
  echo "|---|---|---|"
  # Spine apps are discovered the same way the runner and the schema gate find them: a
  # service.toml one level below the repo root (capabilities/ sit two levels down and have
  # their own section above). Glob, not a hand-list, so a second spine app can never be
  # silently absent from this table -- same rationale as capability.sh's registry glob.
  for st in "$SJEL_ROOT"/*/service.toml; do
    [ -f "$st" ] || continue          # empty glob -> literal path, skip it
    dir="$(dirname "$st")/"
    name="$(basename "$dir")"
    desc=""
    if [ -f "$dir/README.md" ]; then
      desc="$(awk '/^# /{h=1;next} h{ if (!NF) { if (got) exit; else next }; got=1; printf "%s ", $0 }' "$dir/README.md")"
      trimmed="${desc%%. *}"
      if [ "$trimmed" != "$desc" ]; then desc="$trimmed."; else desc="${desc% }"; fi
    fi
    port="—"
    p="$(toml_get port "$st")"
    if [ -n "$p" ]; then port="\`$p\`"; fi
    echo "| \`$name\` | $desc | $port |"
  done
  echo

  echo "## Libs"
  echo
  echo "Spine-owned shared code with no domain of its own — statically linked into capability"
  echo "binaries at compile time. See [Three architectural nouns](CONTRIBUTING.md#three-architectural-nouns)."
  echo
  echo "| Lib | What |"
  echo "|---|---|"
  for dir in "$SJEL_ROOT"/libs/*/; do
    [ -d "$dir" ] || continue
    name="$(basename "$dir")"
    desc=""
    if [ -f "$dir/README.md" ]; then
      desc="$(awk '/^# /{h=1;next} h{ if (!NF) { if (got) exit; else next }; got=1; printf "%s ", $0 }' "$dir/README.md")"
      trimmed="${desc%%. *}"
      if [ "$trimmed" != "$desc" ]; then desc="$trimmed."; else desc="${desc% }"; fi
    fi
    echo "| \`$name\` | $desc |"
  done
  echo

  echo "## Packs"
  echo
  echo "| Pack | Description | Skills | Drives |"
  echo "|---|---|---|---|"
  for toml in "$SJEL_ROOT"/Packs/*/pack.toml; do
    [ -f "$toml" ] || continue
    pname="$(toml_get name "$toml")"
    pdesc="$(toml_get description "$toml")"
    skills="$(toml_array skills "$toml" | tr '\n' ',' | sed 's/,$//; s/,/, /g')"
    caps="$(toml_array capabilities "$toml" | tr '\n' ',' | sed 's/,$//; s/,/, /g')"
    if [ -z "$caps" ]; then caps="—"; fi
    echo "| \`$pname\` | $pdesc | $skills | $caps |"
  done
  echo

  echo "## State mounts"
  echo
  echo "Where tools actually persist data — Axon records where a tool already writes, it never"
  echo "relocates the directory (see [State mounts record reality](CONTRIBUTING.md#state-mounts-record-reality))."
  echo
  echo "**Not tabulated here.** The \`[[state_mount]]\` registry moved from \`axon.toml\` into"
  echo "\`<overlay>/config/machine.toml\` on 2026-07-26, because those paths describe one machine"
  echo "and this file is the shared repo snapshot — a generated public document cannot carry a"
  echo "second machine's home directory. Run \`tools/doctor\` to see this machine's"
  echo "mounts and whether each path exists. See"
  echo "schemas/machine.toml.example."
  echo

  echo "## Upstreams by verdict"
  echo
  # The verdict vocabulary is declared exactly once, in upstreams.toml's own header
  # ('# verdict = "a" | "b" | ...') -- parse it from there instead of restating it, so
  # adding a verdict class means editing that one line and this section follows.
  verdicts="$(sed -n 's/^# verdict = //p' "$UP" | tr -d '"|')"
  if [ -z "$verdicts" ]; then
    echo "generate-architecture: cannot parse verdict vocabulary from upstreams.toml header" >&2
    exit 1
  fi
  for v in $verdicts; do
    names=""
    for s in $(toml_sections "$UP"); do
      vv="$(toml_get_in "$s" verdict "$UP")"
      if [ "$vv" = "$v" ]; then
        if [ -z "$names" ]; then names="$s"; else names="$names, $s"; fi
      fi
    done
    if [ -z "$names" ]; then continue; fi
    echo "- **$v**: $names"
  done
  echo

  echo "## Systems"
  echo
  echo "| System | Kind | Local | Why |"
  echo "|---|---|---|---|"
  for s in $(toml_sections "$SYS"); do
    kind="$(toml_get_in "$s" kind "$SYS")"
    local_="$(toml_get_in "$s" local "$SYS")"
    why="$(toml_get_in "$s" why "$SYS")"
    echo "| \`$s\` | $kind | $local_ | $why |"
  done
  echo

  echo "## Dependency graph"
  echo
  echo "Generated from the same manifests as the tables above — each Pack's declared"
  echo "\`capabilities\` (drives) and \`links\` (systems its skill actually talks to), plus"
  echo "every capability's pinned upstream image. This shows what's wired, not full"
  echo "inventory — see the Capabilities/Packs/Systems tables above for that."
  echo
  echo '```mermaid'
  echo "flowchart LR"
  for toml in "$SJEL_ROOT"/Packs/*/pack.toml; do
    [ -f "$toml" ] || continue
    pname="$(toml_get name "$toml")"
    pid="pack_${pname//[^A-Za-z0-9]/_}"
    echo "  $pid([\"$pname\"])"
    for cap in $(toml_array capabilities "$toml"); do
      cid="cap_${cap//[^A-Za-z0-9]/_}"
      echo "  $pid --> $cid[\"$cap\"]"
    done
    for link in $(toml_array links "$toml"); do
      lid="sys_${link//[^A-Za-z0-9]/_}"
      echo "  $pid -.-> $lid((\"$link\"))"
    done
  done
  for dir in "$SJEL_ROOT"/capabilities/*/; do
    [ -d "$dir" ] || continue
    name="$(basename "$dir")"
    if [ -f "$dir/service.toml" ]; then
      img="$(toml_get image "$dir/service.toml")"
      tag="$(toml_get tag "$dir/service.toml")"
      if [ -n "$img" ]; then
        cid="cap_${name//[^A-Za-z0-9]/_}"
        iid="img_${img//[^A-Za-z0-9]/_}"
        echo "  $cid[\"$name\"] -->|image| $iid[\"$img:$tag\"]"
      fi
    fi
  done
  # `requires=` edges — what must already be running before this one starts, which is
  # what tools/service-runner.sh actually orders on. These were absent from this diagram
  # until 2026-07-30 even though every one of them was already declared in a manifest the
  # generator opens: the graph showed which Pack drives a capability but not which
  # capability needs another, so postgres looked like a leaf nothing depended on.
  #
  # Dashed, and labelled distinctly from the code-level coupling in self.json: `requires=`
  # means "must be up", not "is compiled in". Conflating the two would misread the spine —
  # dashboard requires sjel-status over HTTP and shares no code with it at all.
  #
  # Both globs: capabilities sit two levels down, the spine's own manifests one level down.
  for st in "$SJEL_ROOT"/capabilities/*/service.toml "$SJEL_ROOT"/*/service.toml; do
    [ -f "$st" ] || continue
    name="$(basename "$(dirname "$st")")"
    cid="cap_${name//[^A-Za-z0-9]/_}"
    for dep in $(toml_array requires "$st"); do
      did="cap_${dep//[^A-Za-z0-9]/_}"
      echo "  $cid[\"$name\"] -.->|requires| $did[\"$dep\"]"
    done
  done
  echo '```'
  echo

  echo "## Code-level dependency graph (local, on demand)"
  echo
  echo "The graph above is manifest-derived and coarse on purpose (Packs/capabilities/images,"
  echo "not functions). For a real, file-and-function-level code graph, run"
  echo "\`tools/graphify.sh\` — output lands in \`graphify-out/\`,"
  echo "git-ignored and never embedded here: graphify's node ids are slugified from this"
  echo "machine's absolute path, so committing any of it would leak that path into a public"
  echo "repo. See tools/graphify.sh."
  echo

} > "$OUT"

echo "wrote $OUT"
